### PR TITLE
Netlib WebSockets take 1

### PR DESCRIPTION
**Pull request by Chandler**
Hello mitmproxy!

This PR introduces the beginnings of a RFC-06455 WebSockets library in netlib.

I've tried to style it like the rest of netlib in a very modular and readable fashion. As more concrete needs for the library arise we will have a better picture for what needs to be added, but I think this gives us a nice starting point. 

I've implemented just enough to get a basic echo server integration test passing, which means we've got enough to start manipulating and serializing frames in mitmdump.

I'm not a python dev and I'm fairly new to networking and bit twiddling so I'm not married to any of this and look forward to getting your feedback.

There are obviously many many things that need to be added, beginning with more unit and integration tests and working on pathod. All things I can get started on if this looks like it's going in the right direction.

Eventually, it might be nice for the reference client/server to be correct enough to pass the Autobahn WebSockets tests. http://autobahn.ws/testsuite/

PS if you like this, maybe make a websockets branch in the main netlib repo for me to start sending PRs against?

### CODE REVIEW

**Comment by cortesi** [comment]
This is an excellent beginning. Below are some rough, off-the-top-of-my-head comments. If you don't have time to hack further over the weekend, I'll make some of these adaptations and merge to master, and we can continue from there.

- Please build on the reader and writer implementations in tcp.py directly. Have a look at the implementations in http.py and socks.py to see this style in action. You've already stepped in this direction by parameterising read_bytes in your work, so we're on the same page. It's just that we can have a flatter abstraction. It looks like socks.py has the closest structure to this module, so try to carry over the API and conventions there. 

- The stuff in implementations.py belong in pathod or possibly test suite. Teaching pathod and pathoc about websockets will be quite a bit of work, but will pay huge dividends. We rely on it completely to stress these implementations. I'll start thinking about how to extend the mini-language there to let us craft websocket frames. Exciting.

- We definitely want to maintain 100% line coverage for the netlib unit test suite. So, lots more tests, please. :-)

- Make validate_frame return a bool, and remove the use_validation option from the constructor. We can call validation if we want to know if the frame is valid and take it out of places like to_bytes. 

- It looks to me like the constructor should do a lot of the work that the default_frame_from_message currently does. 

- from_bytes and from_byte_stream can collapse if we're using the tcp.py abstractions directly.

**Comment by mhils** [comment]
:+1:
Excited for this. :smile:

**Comment by Chandler** [comment]
hey thanks for the fast reply.

I have some time this weekend, but how about I focus on addressing the test coverage and I'll take your offer to let you to make some of those changes (I gave you push access on my fork so you can update this PR)

**Comment by Chandler** [comment]
made some small changes, still working on lots more tests.

> Make validate_frame return a bool
Done, with safe_to_bytes() option

> The stuff in implementations.py belong in pathod or possibly test suite.
pathod will be great so we can use them to test mitmproxy, but I guess I'll put it in the tests directory in the meantime. 

Might be kind of cool to also make the netlib unit tests importable by other projects so we could run all of the netlib websocket tests through a mitmproxy just to prove that it doesn't interfere with anything

>It looks to me like the constructor should do a lot of the work that the default_frame_from_message currently does.
The constructor just allows setting of the values without any logic so that the default builder and the byte_reader can build frames as they choose. Not seeing a great way to make the constructor act like default() and still be able to construct the object from raw values.

**Comment by mhils** [comment]
Great work :+1: :smile:

**Comment by cortesi** [comment]
Great work - thanks! Lets continue this on master. :)

**Pull request merged**
