### PR TITLE
Only set content length if not available

### PR DESCRIPTION
**Pull request by jvillacorta**

### CODE REVIEW

**Comment by jvillacorta** [comment]
test_content_length_update implies that in all requests the content-length should match the actual content size which is not true for HEAD requests.  I could check if content is empty and content-length is greater than 0 then not change the content-length but I am not sure if this will break anything else

**Comment by mhils** [comment]
It's intentional that `request.content` auto-updates (and overwrites) the content-length header. Internally, we should however update `request.data.content` directly, which we apparently don't do at some point.

**Comment by jvillacorta** [comment]
Ok so if I get what you are saying, is that ```request.data.content``` is the one that should auto update the content-length header always while the ``response.data.content``` should have logic to avoid replacing the header in cases were content is not present but the content-length is sent (HEAD requests) or maybe even not auto-update the header on responses all together.

This will still not pass that test though.

**Comment by mhils** [comment]
Sorry for the late reply. Slightly corrected version of your previous post:

`message.content` (message = request/response) is the one that should auto update the content-length header always while the `message.data.content` should not auto-update the header on responses all together. 

If you think a test is faulty, please fix it. As I see it, `test_content_length_update` just verifies that `message.content` always updates the header.

**Pull request closed without merging**
