### PR TITLE
Adding support for upstream certificate validation when using SSL/TLS…

### PR DESCRIPTION
**Pull request by kyle-m**
… with an instance of TCPClient. Allows for specifying any of the PyOpenSSL VERIFY_* options found [here](https://pyopenssl.readthedocs.org/en/latest/api/ssl.html#OpenSSL.SSL.VERIFY_NONE). Also allows for the default OpenSSL trusted CAs to be overridden.

This commit is intended to be followed by a commit adding an optional flag to mitmproxy which leverages this feature. Relates to the feature request found here: https://github.com/mitmproxy/mitmproxy/issues/558.

### CODE REVIEW

**Comment by cortesi** [comment]
Excellent, thanks. This has long been on our todo list. Do you have plans to work on the mitmproxy side of this at all?

**Comment by kyle-m** [comment]
Yes! I have a patch in progress and all I have left is to finish fully testing the functionality so keep an eye out for a pull request soon.

**Comment by cortesi** [comment]
Good stuff. Drop me a line if you'd like an invite to the developer Slack to brainstorm any of this.

**Comment by mhils** [comment]
Great work! :smile: 
I think it would be worthwhile to include [certifi](http://certifi.io/en/latest/) as a default trust database, maybe even already in netlib?

**Comment by cortesi** [comment]
Yes, I think that's a good idea. I'd like to have validation for pathoc, even if we only give debug feedback on certificate validity to the user.

The other complicated issue here is what to do with validation failures in mitmproxy - on or off by default, fail connections outright or try to reflect the behaviour to the user, and so forth. Let's see what Kyle comes up with. :)

**Comment by kyle-m** [comment]
Sorry for the delayed response, had to put this aside for the moment to work on something else. 

I can add in certifi as the default trusted CA bundle so long as you don't mind the added dependency. The change is fairly trivial so I'll submit a PR for it momentarily.

If you wanted to enable debug information for certificate validity through pathoc I imagine it would be useful to tweak the behavior slightly. You could always perform certificate verification in TCPClient and then store the results in state somewhere. Then you could use the parameter to optionally make the connection attempt fail in the verify callback, that way you could present feedback without having to end the connection. 

With respect to the mitmproxy piece I'd be happy to chat about details if you want to send me an invite to the Slack, I would be curious to hear your guys' feedback given there are so many ways to handle failures.

**Comment by cortesi** [comment]
Hi Kyle. Thanks for your work here - I've just fired through an invite to the mitmproxy Slack instance where we can brainstorm about the best way to approach the mitmproxy end of things.

**Pull request merged**
